name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    paths:
      - "./deploy/*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sign into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Lint Bicep
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az bicep build --file ./deploy/main.bicep
  validate:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sign into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get existing images
        id: getimages
        run: |
          echo "Installing containerapp extension"
          az extension add -n containerapp --yes
          inventoryApiImage=$(az containerapp show --name inventoryapi --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)
          bookApiImage=$(az containerapp show --name booksapi --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)          
          echo "::set-output name=inventoryApiImage::$inventoryApiImage"
          echo "::set-output name=bookApiImage::$bookApiImage"

      - name: Run preflight validation
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./deploy/main.bicep
          deploymentMode: Validate
          parameters: inventoryApiImage=${{ steps.getimages.outputs.inventoryApiImage }} bookApiImage=${{ steps.getimages.outputs.bookApiImage }}

  preview:
    needs: [lint, validate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        name: Sign into Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get existing images
        id: getimages
        run: |
          echo "Installing containerapp extension"
          az extension add -n containerapp --yes
          inventoryApiImage=$(az containerapp show --name inventoryapi --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)
          bookApiImage=$(az containerapp show --name booksapi --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)
          echo "::set-output name=inventoryApiImage::$inventoryApiImage"
          echo "::set-output name=bookApiImage::$bookApiImage"
      
      - uses: Azure/cli@v1
        name: Run what-if
        with:
          inlineScript: |
            az deployment group what-if --resource-group ${{ secrets.AZURE_RG }} --template-file ./deploy/main.bicep --parameters inventoryApiImage=${{ steps.getimages.outputs.inventoryApiImage }} bookApiImage=${{ steps.getimages.outputs.bookApiImage }}
  
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    needs: preview
    steps:
      - uses: actions/checkout@v2

      - name: Sign into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get existing images
        id: getimages
        run: |
          echo "Installing containerapp extension"
          az extension add -n containerapp --yes
          inventoryApiImage=$(az containerapp show --name inventoryapi --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)
          bookApiImage=$(az containerapp show --name booksapi --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)
          echo "::set-output name=inventoryApiImage::$inventoryApiImage"
          echo "::set-output name=bookApiImage::$bookApiImage"

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./deploy/main.bicep
          deploymentMode: Incremental
          parameters: inventoryApiImage=${{ steps.getimages.outputs.inventoryApiImage }} bookApiImage=${{ steps.getimages.outputs.bookApiImage }}